### ISSUE TITLE
Animate segment circle changes

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#8]
Changes on the balance's segment circle are not animated and happen abruptly.

**Comment by tsejerome** [comment]
@aguycalled 

Hypothesis: The reason that it is not animated is because we are replacing the arc object directly and the whole thing rerenders.

Before I do modifications, I want to double confirm the current logics at `<SegmentCircle/>`.

The current logic of `<SegmentCircle/>`:
1. Check the props `segments`, which is an array of color and size, where `color` is defined at `constants/theme/appTheme.json` and size is a number from 0 to 100 
2. If `syning` is true, there will only be 1 or 2 item in the `segments` array.
3. If `syning` is false, it's either default state or loaded state. If it is loaded state, it is possible to have 3 colors (3 parts of arc) in the circle as it cud be nav, xnav and staked.

**Comment by tsejerome** [comment]
> > 2. If `syning` is true, there will only be 1 or 2 item in the `segments` array.
> 
> there will always be 2 items, with the second being the remaining syncing progress (100 - item[0])
> 
I saw that the default state got only 1 item tho?

**Comment by aguycalled** [comment]
when syncing it should be 2:

BalanceCircle.tsx: 


```
      <SegmentCircle
        radius={width / 2 - 100}
        segments={
          syncing
            ? [
                {
                  size: syncProgress,
                  color: theme['color-nav-pink'],
                },
                {
                  size: 100 - syncProgress,
                },
              ]
            : balanceSegments
        }
        totalArcSize={353}
      />
```

**Comment by tsejerome** [comment]
I don't quite agree, from what I see from the UI.
It seems that by default `syncing` is false, so the default state is being used.
```
 const [balanceSegments, setBalanceSegments] = useState([
    {
      size: 0,
      color: theme['color-nav-pink'],
    },
  ]);
```

I believe that that the user might be confused and the default state shd be grayed out and being synchronized.

**Comment by aguycalled** [comment]
Yes, you are right sorry I've missed that. I understand that's the value before the wallet has been loaded and started syncing.

**Comment by aguycalled** [comment]
Maybe we could have something like this:

https://dribbble.com/shots/14513476-Infinite-loading

While the wallet gets loaded/is in connecting state

**Comment by tsejerome** [comment]
> Maybe we could have something like this:
> 
> https://dribbble.com/shots/14513476-Infinite-loading
> 
> While the wallet gets loaded/is in connecting state

Oh shit, totally miss this message. I used the circular progress at last
